/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.accure.payroll.dto;


import com.accure.hrms.dto.EarningHeadsDetails;
import com.accure.usg.common.dto.Common;
import java.util.List;

/**
 *
 * @author upendra
 */
public class ArrearProcess extends Common {

   // private List<Employee> arrearprocessedList;
    private String sortBy;
    private int payMonth;
    private String arrearType;
    private int payYear;
    private String fromDate;
    private String toDate;
    private String orderno;
    private int month;
    private int year;
    private int openBalance;
    private String finacialYear;
    private String employeeCode;
    private String employeeCodeM;
    private String employeeName;
    private String location;
    private String locationName;
    private String department;
    private String departmentName;
    private String designation;
    private String designationName;
    private String salaryType;
    private String salaryTypeName;
    private String ddo;
    private String ddoName;
    private String natureType;
    private String postingCity;
    private String pfType;
    private String fundType;
    private String fundTypeName;
    private String budgetHead;
    private String budgetHeadName;
    private long earnings;
    private long deductions;
    private int fromYear;
    private int fromMonth;
    private int toMonth;
    private int toYear;
    private String arrearStatus;
    private boolean lockStatus;
    private boolean sendToAccountStatus;
    private List<EarningHeadsDetails> earningHeads;
    private List<EarningHeadsDetails> deductionHeads;
    private List<EarningHeadsDetails> prevEarningHeads;
    private List<EarningHeadsDetails> prevDeductionHeads;
     private List<EarningHeadsDetails> diffEarningHeads;
    private List<EarningHeadsDetails> diffDeductionHeads;
    private double totalEarnings;
    private double totalDeductions;
    private double netPay;
    private String autoGeneratedBillNo;
     private long billSlNo=0;
    private String manualBillNo;
    private String billDate;
    private long fromDateInMilliSecond;
    private long toDateInMilliSecond;
    

    public String getAutoGeneratedBillNo() {
        return autoGeneratedBillNo;
    }

    public void setAutoGeneratedBillNo(String autoGeneratedBillNo) {
        this.autoGeneratedBillNo = autoGeneratedBillNo;
    }

    public long getBillSlNo() {
        return billSlNo;
    }

    public void setBillSlNo(long billSlNo) {
        this.billSlNo = billSlNo;
    }

    
    public String getManualBillNo() {
        return manualBillNo;
    }

    public void setManualBillNo(String manualBillNo) {
        this.manualBillNo = manualBillNo;
    }

    public String getBillDate() {
        return billDate;
    }

    public void setBillDate(String billDate) {
        this.billDate = billDate;
    }

    public String getBudgetHeadName() {
        return budgetHeadName;
    }

    public void setBudgetHeadName(String budgetHeadName) {
        this.budgetHeadName = budgetHeadName;
    }
    public boolean isSendToAccountStatus() {
        return sendToAccountStatus;
    }

    public void setSendToAccountStatus(boolean sendToAccountStatus) {
        this.sendToAccountStatus = sendToAccountStatus;
    }
    public double getTotalEarnings() {
        return totalEarnings;
    }

    public void setTotalEarnings(double totalEarnings) {
        this.totalEarnings = totalEarnings;
    }

    public double getTotalDeductions() {
        return totalDeductions;
    }

    public void setTotalDeductions(double totalDeductions) {
        this.totalDeductions = totalDeductions;
    }

    public double getNetPay() {
        return netPay;
    }

    public void setNetPay(double netPay) {
        this.netPay = netPay;
    }
    public int getOpenBalance() {
        return openBalance;
    }

    public void setOpenBalance(int openBalance) {
        this.openBalance = openBalance;
    }
    public List<EarningHeadsDetails> getDeductionHeads() {
        return deductionHeads;
    }

    public void setDeductionHeads(List<EarningHeadsDetails> deductionHeads) {
        this.deductionHeads = deductionHeads;
    }
    private String arrearDate;

    public String getFinacialYear() {
        return finacialYear;
    }

    public void setFinacialYear(String finacialYear) {
        this.finacialYear = finacialYear;
    }
    
    public String getArrearDate() {
        return arrearDate;
    }

    public void setArrearDate(String arrearDate) {
        this.arrearDate = arrearDate;
    }

    public int getFromMonth() {
        return fromMonth;
    }

    public void setFromMonth(int fromMonth) {
        this.fromMonth = fromMonth;
    }

    public String getDdoName() {
        return ddoName;
    }

    public void setDdoName(String ddoName) {
        this.ddoName = ddoName;
    }

    public int getFromYear() {
        return fromYear;
    }

    public void setFromYear(int fromYear) {
        this.fromYear = fromYear;
    }

    public int getToMonth() {
        return toMonth;
    }

    public void setToMonth(int toMonth) {
        this.toMonth = toMonth;
    }

    public int getToYear() {
        return toYear;
    }

    public void setToYear(int toYear) {
        this.toYear = toYear;
    }
    

    public List<EarningHeadsDetails> getEarningHeads() {
        return earningHeads;
    }

    public void setEarningHeads(List<EarningHeadsDetails> earningHeads) {
        this.earningHeads = earningHeads;
    }

    public boolean getLockStatus() {
        return lockStatus;
    }

    public List<EarningHeadsDetails> getPrevEarningHeads() {
        return prevEarningHeads;
    }

    public void setPrevEarningHeads(List<EarningHeadsDetails> prevEarningHeads) {
        this.prevEarningHeads = prevEarningHeads;
    }

    public List<EarningHeadsDetails> getPrevDeductionHeads() {
        return prevDeductionHeads;
    }

    public void setPrevDeductionHeads(List<EarningHeadsDetails> prevDeductionHeads) {
        this.prevDeductionHeads = prevDeductionHeads;
    }
    
    public void setLockStatus(boolean lockStatus) {
        this.lockStatus = lockStatus;
    }

    public List<EarningHeadsDetails> getDiffEarningHeads() {
        return diffEarningHeads;
    }

    public void setDiffEarningHeads(List<EarningHeadsDetails> diffEarningHeads) {
        this.diffEarningHeads = diffEarningHeads;
    }

    public List<EarningHeadsDetails> getDiffDeductionHeads() {
        return diffDeductionHeads;
    }

    public void setDiffDeductionHeads(List<EarningHeadsDetails> diffDeductionHeads) {
        this.diffDeductionHeads = diffDeductionHeads;
    }
    
    public String getArrearStatus() {
        return arrearStatus;
    }

    public void setArrearStatus(String arrearStatus) {
        this.arrearStatus = arrearStatus;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getEmployeeCodeM() {
        return employeeCodeM;
    }

    public void setEmployeeCodeM(String employeeCodeM) {
        this.employeeCodeM = employeeCodeM;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public String getSalaryType() {
        return salaryType;
    }

    public void setSalaryType(String salaryType) {
        this.salaryType = salaryType;
    }

    public String getDdo() {
        return ddo;
    }

    public void setDdo(String ddo) {
        this.ddo = ddo;
    }

    public String getNatureType() {
        return natureType;
    }

    public void setNatureType(String natureType) {
        this.natureType = natureType;
    }

    public String getPostingCity() {
        return postingCity;
    }

    public void setPostingCity(String postingCity) {
        this.postingCity = postingCity;
    }

    public String getPfType() {
        return pfType;
    }

    public void setPfType(String pfType) {
        this.pfType = pfType;
    }

    public String getFundType() {
        return fundType;
    }

    public void setFundType(String fundType) {
        this.fundType = fundType;
    }

    public String getBudgetHead() {
        return budgetHead;
    }

    public void setBudgetHead(String budgetHead) {
        this.budgetHead = budgetHead;
    }

    public long getEarnings() {
        return earnings;
    }

    public void setEarnings(long earnings) {
        this.earnings = earnings;
    }

    public long getDeductions() {
        return deductions;
    }

    public void setDeductions(long deductions) {
        this.deductions = deductions;
    }
    public int getMonth() {
        return month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

//    public List<Employee> getArrearprocessedList() {
//        return arrearprocessedList;
//    }
//
//    public void setArrearprocessedList(List<Employee> arrearprocessedList) {
//        this.arrearprocessedList = arrearprocessedList;
//    }

    public String getSortBy() {
        return sortBy;
    }

    public void setSortBy(String sortBy) {
        this.sortBy = sortBy;
    }

    public int getPayMonth() {
        return payMonth;
    }

    public void setPayMonth(int payMonth) {
        this.payMonth = payMonth;
    }

    public String getArrearType() {
        return arrearType;
    }

    public void setArrearType(String arrearType) {
        this.arrearType = arrearType;
    }

    public int getPayYear() {
        return payYear;
    }

    public void setPayYear(int payYear) {
        this.payYear = payYear;
    }

    public String getFromDate() {
        return fromDate;
    }

    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }

    public String getToDate() {
        return toDate;
    }

    public void setToDate(String toDate) {
        this.toDate = toDate;
    }

    public String getOrderno() {
        return orderno;
    }

    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    public String getLocationName() {
        return locationName;
    }

    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public String getDesignationName() {
        return designationName;
    }

    public void setDesignationName(String designationName) {
        this.designationName = designationName;
    }

    public String getSalaryTypeName() {
        return salaryTypeName;
    }

    public void setSalaryTypeName(String salaryTypeName) {
        this.salaryTypeName = salaryTypeName;
    }

    public String getFundTypeName() {
        return fundTypeName;
    }

    public void setFundTypeName(String fundTypeName) {
        this.fundTypeName = fundTypeName;
    }

    public long getFromDateInMilliSecond() {
        return fromDateInMilliSecond;
    }

    public void setFromDateInMilliSecond(long fromDateInMilliSecond) {
        this.fromDateInMilliSecond = fromDateInMilliSecond;
    }

    public long getToDateInMilliSecond() {
        return toDateInMilliSecond;
    }

    public void setToDateInMilliSecond(long toDateInMilliSecond) {
        this.toDateInMilliSecond = toDateInMilliSecond;
    }
    

}
